// This file was generated by counterfeiter
package v2fakes

import (
	"sync"

	"code.cloudfoundry.org/cli/actors/configactions"
	"code.cloudfoundry.org/cli/commands/v2"
)

type FakeAPIConfigActor struct {
	SetTargetStub        func(CCAPI string, skipSSLValidation bool) (string, configactions.Warnings, error)
	setTargetMutex       sync.RWMutex
	setTargetArgsForCall []struct {
		CCAPI             string
		skipSSLValidation bool
	}
	setTargetReturns struct {
		result1 string
		result2 configactions.Warnings
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAPIConfigActor) SetTarget(CCAPI string, skipSSLValidation bool) (string, configactions.Warnings, error) {
	fake.setTargetMutex.Lock()
	fake.setTargetArgsForCall = append(fake.setTargetArgsForCall, struct {
		CCAPI             string
		skipSSLValidation bool
	}{CCAPI, skipSSLValidation})
	fake.recordInvocation("SetTarget", []interface{}{CCAPI, skipSSLValidation})
	fake.setTargetMutex.Unlock()
	if fake.SetTargetStub != nil {
		return fake.SetTargetStub(CCAPI, skipSSLValidation)
	} else {
		return fake.setTargetReturns.result1, fake.setTargetReturns.result2, fake.setTargetReturns.result3
	}
}

func (fake *FakeAPIConfigActor) SetTargetCallCount() int {
	fake.setTargetMutex.RLock()
	defer fake.setTargetMutex.RUnlock()
	return len(fake.setTargetArgsForCall)
}

func (fake *FakeAPIConfigActor) SetTargetArgsForCall(i int) (string, bool) {
	fake.setTargetMutex.RLock()
	defer fake.setTargetMutex.RUnlock()
	return fake.setTargetArgsForCall[i].CCAPI, fake.setTargetArgsForCall[i].skipSSLValidation
}

func (fake *FakeAPIConfigActor) SetTargetReturns(result1 string, result2 configactions.Warnings, result3 error) {
	fake.SetTargetStub = nil
	fake.setTargetReturns = struct {
		result1 string
		result2 configactions.Warnings
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAPIConfigActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.setTargetMutex.RLock()
	defer fake.setTargetMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeAPIConfigActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v2.APIConfigActor = new(FakeAPIConfigActor)
